### ISSUE TITLE
db to markdown file script

### ISSUE THREAD

**Issue by sanketgarade** [mukta-strot/marathi-shabd#2]
- input file will be the db.csv
- output will be a markdown file which will be used on the github pages website. for now it will the be the home page of the site.
- for now, a user will have to manual search for a word of interest (or can also use the browser's search function.)

**Comment by shreyasg-git** [comment]
markdown मध्ये का रुपांतर करायचे आहे? जर csvला embed करायचा पर्याय नाहीये का?

**Comment by sanketgarade** [comment]
@shreyasg-git markdown केलं तर website चे formatting चांगलं करता येईल. नुसती csv तशी चा तशी टाकली तर चांगली नाही दिसणार असं मला वाटतं. वरून csv मध्ये खूप कच्चा डेटा असेल. तुझा कडे काही चांगली कल्पना असेल तर सुचावं .

**Comment by sanketgarade** [comment]
prerequisites -
- have a csv file with content in en and mr columns
- have a template markdown file for the output

steps -

1. read the csv file
2. create a new markdown file from the template
3. extract the en and mr words from a row of the csv
4. fill the extracted words in the markdown file
5. repeat 3-4 till all rows of csv are done

**Comment by shreyasg-git** [comment]
why markdown then? we can directly make HTML from csv, It will be easier to do because markdowns are messy

**Comment by sanketgarade** [comment]
is it? i don't have much idea tbh. I personally find working with md easy. but if you think html is better and you can contribute for developing it then we decide for it. also converting from md to html (and vice versa) is possible and easy with pandoc i think (in case we have to try out both options).

**Comment by shreyasg-git** [comment]
If we figure out some way to convert csv to html directly using JS then that will be the best...but I think we dont have to stick to HTML tables...we can make our own components which will give us more flexibility in case of colors, styles etc

**Comment by sanketgarade** [comment]
I was actually considering to do this using python since I have some exp with it. Also the target is to keep it extremely lightweight, basic and simple like [this website](https://based.cooking/).

**Comment by shreyasg-git** [comment]
How are you planning to do this with Python? I am not sure if we can run python in browser so we will have setup backend for running python ?

**Comment by sanketgarade** [comment]
- Python will simply be used to create the markdown files from the csv raw data. (This is the crux of the coding part.)
- the static web pages (HTML pages) will then be created using a static site builder (GitHub pages uses Jekyll I think) and the previously created MD files. 
- The website will then be hosted on GitHub pages. 

There will be no dynamic components or any code/script that will run in the browser when the website is visited. It will be completely static like the site I showed in the previous comment.

**Comment by shreyasg-git** [comment]
sounds good 👍

**Comment by sanketgarade** [comment]
Closing this issue as this turned into a generic discussion. Also same points mentioned in a new issue.
