### ISSUE TITLE
Website styling

### ISSUE THREAD

**Issue by sanketgarade** [mukta-strot/marathi-shabd#27]
- all pages to have same styling
- for now, use the home page style as a reference. (No explicit styling has been applied there. It's the default style without any theme being applied.) 
- static pages must be able to be viewed without any issues even if the user turns on "reader mode" on their browser.

**Comment by the-kaustubh** [comment]
Home page is styled based on github markdown, this is done by github automatically. Do you want to replicate similar styling for the static site?

**Comment by sanketgarade** [comment]
> Home page is styled based on github markdown, this is done by github automatically. Do you want to replicate similar styling for the static site?

Yes. Btw the homepage is also a static site. So lets have some names to avoid confusion. The search functionality and related web pages that you are developing- lets call them "search site". Home page and other documentation is "home site" and browse pages will be "browse site". 😬

@zarbod FYI also. 
Though for markdown files we won't have to do anything explicitly, I think.

**Comment by sanketgarade** [comment]
> Home page is styled based on github markdown, this is done by github automatically. Do you want to replicate similar styling for the static site?

Yes. Btw the homepage is also a static site. So lets have some names to avoid confusion. The search functionality and related web pages that you are developing- lets call them "search site". Home page and other documentation is "home site" and browse pages will be "browse site". 😬

@zarbod FYI also. 
Though for markdown files we won't have to do anything explicitly, I think.
