### ISSUE TITLE
Search by tags

### ISSUE THREAD

**Issue by sanketgarade** [mukta-strot/marathi-shabd#28]
Each word has one or more tags, which are like categories under which the word falls. 

On the "**search**" page, Give user the option of searching such categories. Since the categories will be limited by those in the database, only those should be made available to search. The search (more like selection) can be done via a drop down menu.

(The list for the drop down menu itself can be created by parsing the tags present in the database.)

Once user selects a particular tag from the menu, they should be shown all the word-blocks for the words that fall under that tag.

**Comment by merqrial** [comment]
खूप जास्त कॅटेगरी झाल्या तर कसं होईल? की कॅटेगरी चा संच संपादित असेल?

**Comment by sanketgarade** [comment]
वर्ग/विषय यांची संख्या खूप वाढली तर काय करायचं याचा विचार अजुन केला नाहीये. तुम्ही तुमची कल्पना सुचवू शकता. 

सध्यातरी विचार असा आहे की डेटाबेस मध्ये नोंद असलेल्या सगळ्या वर्ग/विषयांची एक यादी बनवायची. (BROWSE विभागात वापरण्यासाठी ती आता ही स्वयं-निर्मित केली जाते.)
या मुळे विषयांचा संच हा संपादित (म्हणजे डेटाबेस वर अवलंबून) असेल.

**Comment by shaanguptaa** [comment]
Can I try this?

**Comment by sanketgarade** [comment]
> Can I try this?

sure.

**Comment by shaanguptaa** [comment]
I created this pull request #76 adding this feature just a few days ago.
Can you please review it, and if you have any feedback or if there's anything needed, please let me know.

**Comment by sanketgarade** [comment]
thanks. i didn't review the code but merged and tested it. It works fine. The same (`develop` branch) is deployed to the github pages site.
