### ISSUE TITLE
sorting of db file

### ISSUE THREAD

**Issue by sanketgarade** [mukta-strot/marathi-shabd#3]
- the db file needs to be sorted using the english word column
- sort order will be A at top and Z at bottom

**Comment by sanketgarade** [comment]
[sort function should be generic](https://github.com/mukta-strot/marathi-shabd/issues/14#issuecomment-876212690)

**Comment by sanketgarade** [comment]
@zarbod about the sorting functionality I have some idea about how we can put it to use in a better way. It'll need some changes. 

Basically the requirements are as follows -

- Words in `All.md` should be sorted alphabetically by the English word. 
- Words in **each topic file** e.g. `science.md` should be sorted alphabetically by the English word. 
- Words in **each alphabet file** e.g. `a.md` should be sorted alphabetically by the English word. 


Also this should happen even if the database is not in a sorted order. Which means that we need to do sorting on the read `db.csv` every time we run `main.py`, but the original `db.csv` should be unchanged. 

Any ideas how this can be done?

**Comment by zarbod** [comment]
I think I can write a sorting script that just returns a sorted row_list like I did for the filter script. In fact, I can add the sorting function to the filter script itself and run it before every filter.
