### ISSUE TITLE
search site - hitting "enter" key should do same as pressing the "search" button

### ISSUE THREAD

**Issue by sanketgarade** [mukta-strot/marathi-shabd#38]
On the search site, currently the user needs to enter the word in the textbox and then click on "search" button to actually begin the search function. 

This can be improved slightly by running the search function directly when users presses the "Enter" key on his keyboard.

**Comment by zarbod** [comment]
https://www.codexworld.com/how-to/trigger-button-click-on-enter-key-press-javascript/ we could add something like this. I'll try it on my end. I don't have any experience with JS so it will be pretty experimental.
