### ISSUE TITLE
Markdown Word block update

### ISSUE THREAD

**Issue by sanketgarade** [mukta-strot/marathi-shabd#40]
Template file (word-template.MD) is updated in template folder. 
@zarbod can you please update the gen block script to output the block in the updated format?

This block basically is updated due to the new columns in the database.

**Comment by sanketgarade** [comment]
on `develop`, the folder structure is updated and the output file must now be passed as an argument to the gen-out script.

**Comment by zarbod** [comment]
PR #47 added to resolve this

**Comment by sanketgarade** [comment]
closing this as its fixed in the above mentioned PR.
