### ISSUE TITLE
remove header row from csv when used for markdown file generation

### ISSUE THREAD

**Issue by sanketgarade** [mukta-strot/marathi-shabd#41]
currently all md files generated using the python scripts has the header row of "en" and "mr" in it.
It (the csv header row) should be removed at the top level function where it is read for the first time.

**Comment by sanketgarade** [comment]
Currently skipped using [this method](https://www.foxinfotech.in/2018/09/python-how-to-skip-first-line-in-csv.html)

`next(csv_header)`

Not sure if this is the best way. If there is any better way, that can be done as well.

**Comment by sanketgarade** [comment]
@zarbod can you pls check this and let me know if ok to close this issue. The fix is applied already.

**Comment by zarbod** [comment]
Just checked on my end, it works. I'll close the issue.
