### ISSUE TITLE
topics parser

### ISSUE THREAD

**Issue by sanketgarade** [mukta-strot/marathi-shabd#43]
- parse the database [db.csv](https://github.com/mukta-strot/marathi-shabd/blob/develop/database/db.csv) file `tags` column and extract the individual tags (topics) from it.
- if there are multiple tags (separated by semicolons) those also need to be separately extracted
- duplicates should be removed
- the output of this parser should be a list of tags in a string array separated by a delimiter (comma for now)
- this string array can be later used in the [main.py](https://github.com/mukta-strot/marathi-shabd/blob/develop/browse/scripts/main.py) script to generated output files by topic (which are currently hardcoded.)

**Comment by masonwoodford** [comment]
Hello could I work on this?

**Comment by sanketgarade** [comment]
> Hello could I work on this?

Yes sure. Let me know if you need any inputs. Thanks 😊

**Comment by masonwoodford** [comment]
Where would you like this function to be located?

**Comment by sanketgarade** [comment]
Check the `develop` branch. All source files are inside the `/browse/scripts` folder. You can add it there. It has to be a standalone function to be run on the database csv file and it should output a text string. 

Once the above basic functionality is ready it can be integrated into the `main.py` function. This is the secondary part. This can be done after the above primary part is working ok.

**Comment by masonwoodford** [comment]
Submitted pull request please give me any feedback thank you!

**Comment by sanketgarade** [comment]
once your primary part is done, and if you would like to continue with the secondary part then - I have updated the `main.py` file with some pseudo code which can help with it. Do check it and let me know if you plan to continue on it.

**Comment by sanketgarade** [comment]
Closing this issue as it is fixed in PR #46 and #48. 

Thanks a lot @masonwoodford 😊
