### ISSUE TITLE
remove python cache folder __pycache__

### ISSUE THREAD

**Issue by sanketgarade** [mukta-strot/marathi-shabd#44]
a cache folder gets created everytime a python script is run. Is there a way to prevent this from being created? If not then can be deleted after the scripts are executed? If that too is not possible, then probably this can be added to gitignore.

**Comment by zarbod** [comment]
This should be resolved with the command <find . | grep -E "(__pycache__|\.pyc|\.pyo$)" | xargs rm -rf>, I just need to figure out where to place it.

**Comment by zarbod** [comment]
According to [this](https://stackoverflow.com/questions/28991015/python3-project-remove-pycache-folders-and-pyc-files) on Stackoverflow, the commands `python3 -Bc "import pathlib; [p.unlink() for p in pathlib.Path('.').rglob('*.py[co]')]"
python3 -Bc "import pathlib; [p.rmdir() for p in pathlib.Path('.').rglob('__pycache__')]"` should prevent python from generating any .pyc files. I'll test it later.

**Comment by sanketgarade** [comment]
Ok. From my understanding, it looks like this command needs to be run manually every time you want to remove that folder, isn't it?

**Comment by YashKandalkar** [comment]
It is usually fine to keep these folders in our local environment, and not push them in our remote git repo. As this is just the compiled version of your scripts which will help them run a little faster on a later run.
The `__pycache__/` folder is already present in the [.gitignore](https://github.com/mukta-strot/marathi-shabd/blob/33049ac3ca33bed3ace739ab4f1b4cf96d521fc8/.gitignore#L9) of this repo, so it won't be pushed on git

**Comment by sanketgarade** [comment]
@YashKandalkar yes I recently added it to the gitignore. 

I am not a python developer so I had no idea if that had any impact on the scripts that's why as a safer option I thought of removing it. 

As per your comment it seems like it's safe to keep it as it is and ignore it in git. If that is the case, then this issue can be closed.

**Comment by sanketgarade** [comment]
@zarbod 
I am closing this for now, since we have gitignored it.
