### ISSUE TITLE
extract topics list in topics-list.md

### ISSUE THREAD

**Issue by sanketgarade** [mukta-strot/marathi-shabd#50]
The [topics list file](https://github.com/mukta-strot/marathi-shabd/blob/main/browse/topics/00-topics-list.md) is currently manually created.

It should be created using a script which uses the [topicsParser](https://github.com/mukta-strot/marathi-shabd/blob/main/browse/scripts/topicsParser.py) script.

Please use the `develop` branch for development.

**Comment by masonwoodford** [comment]
I can try tackling this as well if it is open.

**Comment by sanketgarade** [comment]
sure man. go ahead 😃  TIA

**Comment by sanketgarade** [comment]
and oh btw, the topics list is current looking like a paragraph. It'll be great if you can make that look like 1 topic on 1 line.

**Comment by masonwoodford** [comment]
Not sure how pressing this issue is but I'm pretty busy this week if I don't get to it during the week I will this weekend :)

**Comment by masonwoodford** [comment]
I currently have the markdown file being created properly but do you want the topics to be a clickable link like in the sample file shown?

**Comment by sanketgarade** [comment]
Yes it should be clickable. 

About the priority, weekend is fine. It's not that urgent since the current topic list file is up on the website and has working links. So no worries. 😊

**Comment by sanketgarade** [comment]
fixed by merging PR #60
