### ISSUE TITLE
each browse md file must have a its file name in its heading

### ISSUE THREAD

**Issue by sanketgarade** [mukta-strot/marathi-shabd#56]
- currently the topic files being created have only the word blocks for the words under that topic.
- we need to add a title/heading to each topic file, so that it is easy to understand which topic this file is about.
- this will also be helpful when combining (concatenating) multiple topic files to each other, whenever such a feature is needed in the future.
- the title should be same as name of the file

eg. the title for topic file `science.md` will look like 

## science

by using 

```
# science

... followed by the individual word blocks
```

**Comment by zarbod** [comment]
should be a quick fix. I'll work on it.

**Comment by sanketgarade** [comment]
Sorry. I'd like to change this slightly. Do this for all files, not just topic files. Means all.md as well as all alphabet files.

**Comment by sanketgarade** [comment]
@zarbod can you also please do the new changes I mentioned above? It's low priority by the way.
