### ISSUE TITLE
जाहिरात पत्रकात इंस्टाग्राम खात्याचे नाव सुधारणे

### ISSUE THREAD

**Issue by gokhaleaaroh** [mukta-strot/marathi-shabd#75]
आपले instagram पेज आहे का? नसले, तर बनवूया. Reddit पेक्षा instagram वर जास्त लोक असतात.

**Comment by sanketgarade** [comment]
[आहे ना ईथे](https://www.instagram.com/muktastrot/). 

जास्तीत जास्त लोकांपर्यंत पोहोचवण्यासाठी मदत कर 😊🙏🏽

**Comment by sanketgarade** [comment]
ह्यावरून एक लक्षात आलं. आपल्या पत्रकात खालच्या ओळीत इंस्टाग्राम खात्याचे नाव चुकीचे लिहिले गेले आहे. त्यात मी नंतर सुधार करेन. Mukta.strot नसून MuktaStrot असं हवं.
